export const TitleHeaders: Record<string, string> = {
  "[New Event]": "en",
  "[新建活动]": "zhcn",
}

export const ZhcnLabels: Record<string, string> = {
  "language": "zh-CN",
  "活动 ID": "id",
  "活动名称": "title",
  "活动描述": "description",
  "举办者": "author",
  "支持平台": "platform",
  "VRChat 组名称": "group_name",
  "组 ID": "group_id",
  "活动开始时间": "start",
  "活动结束时间": "end",
  "您的时区": "timezone",
  "活动地点": "location",
  "参加方式": "join",
  "活动要求": "require",
  "活动语言": "language",
  "备注": "note",
  "是否是定期活动？": "regular_event",
  "该活动多久举办一次？": "event_often",
  "定期活动最大持续时间": "maximum_duration",
  "标签": "tags",
  "其他标签": "tags_other_zhcn",
  "其他标签对应的英文": "tags_other",
}

export const EnLabels: Record<string, string> = {
  "language": "en",
  "Event ID": "id",
  "Event Name": "title",
  "Event Description": "description",
  "Event Author": "author",
  "Event Platform": "platform",
  "Group Name": "group_name",
  "Group ID": "group_id",
  "Start Time": "start",
  "End Time": "end",
  "Your Timezone": "timezone",
  "Location": "location",
  "How to Join": "join",
  "Event Require": "require",
  "Event Language": "language",
  "Note": "note",
  "Is Regular Event?": "regular_event",
  "How Often?": "event_often",
  "Regular Event Maximum cycle time": "maximum_duration",
  "Tags": "tags",
  "Other Tags": "tags_other",
}

export const OftenOptions: Record<string, string[]> = {
  "zh-CN": [
    "每周",
    "每两周",
    "每月",
    "每季度",
    "每年",
    "每天",
  ],
  "en": [
    "Every Week",
    "Every Two Weeks",
    "Every Month",
    "Every Season",
    "Every Year",
    "Every Day",
  ],
}

export const Languages: Record<string, string> = {
  "English": "en",
  "French": "fr",
  "German": "de",
  "Italian": "it",
  "Japanese": "ja",
  "Korean": "ko",
  "Spanish": "es",
  "Portuguese": "pt",
  "Brazilian": "pt-BR",
  "Hebrew": "he",
  "Polish": "pl",
  "Toki Pona": "tok",
  "Indonesian": "id",
  "Chinese Simplified": "zh-CN",
  "Chinese Traditional": "zh-HK",
  "Russian": "ru",
  "Swedish": "sv",
  "Dutch": "nl",
  "Ukrainian": "uk",
  "Danish": "da",
  "Norwegian": "no",
  "Thai": "th",
  "Finnish": "fi",
  "Hungarian": "hu",
  "Czech": "cs",
  "Turkish": "tr",
  "Arabic": "ar",
  "Romanian": "ro",
  "Vietnamese": "vi",
}